# Generated by Django 4.2.1 on 2024-09-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='image',
            name='is_main',
            field=models.BooleanField(default=True, verbose_name='Главное изображение товара'),
        ),
    ]
