# Generated by Django 4.2.1 on 2024-08-04 11:59

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteristic',
            options={'verbose_name': 'Характеристика товара', 'verbose_name_plural': 'Характеристики товаров'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товаров'},
        ),
        migrations.AlterField(
            model_name='category',
            name='image_path',
            field=models.ImageField(upload_to='categories/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.ImageField(upload_to='products/images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Цена'),
        ),
    ]
