# Generated by Django 4.2.1 on 2024-09-07 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_salesleaderproduct_newproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newproduct',
            options={'verbose_name': 'Новинки', 'verbose_name_plural': 'Новинки'},
        ),
        migrations.AlterModelOptions(
            name='salesleaderproduct',
            options={'verbose_name': 'Лидеры продаж', 'verbose_name_plural': 'Лидеры продаж'},
        ),
        migrations.AlterModelTable(
            name='newproduct',
            table='shop_new_product',
        ),
        migrations.AlterModelTable(
            name='salesleaderproduct',
            table='shop_sales_leader_product',
        ),
    ]
