# Generated by Django 4.2.1 on 2024-09-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_newproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newproduct',
            options={'verbose_name': 'Новинка', 'verbose_name_plural': 'Новинки'},
        ),
        migrations.AlterModelOptions(
            name='salesleaderproduct',
            options={'verbose_name': 'Лидер продаж', 'verbose_name_plural': 'Лидеры продаж'},
        ),
        migrations.AlterField(
            model_name='category',
            name='translation',
            field=models.CharField(max_length=256, unique=True, verbose_name='Транслитерация названия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='part_number',
            field=models.CharField(max_length=24, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='translation',
            field=models.CharField(max_length=256, unique=True, verbose_name='Транслитерация названия'),
        ),
    ]
