# Generated by Django 4.2.1 on 2024-09-09 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_newproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', unique=True, verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='salesleaderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', unique=True, verbose_name='Товар'),
        ),
    ]
