# Generated by Django 4.2.1 on 2024-09-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_newproduct_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproduct',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='salesleaderproduct',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
    ]
